---
title: "Analysis of Exercism.io problems"
output:
  html_document:
    theme: flatly
---
```{r config, include=FALSE}
library(knitr)
opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
```
```{r setup, include=FALSE}
library(tidyverse)
theme_set(theme_minimal())

library(exercism)
data("problem_specifications")
data("exercises")
```

# Number of test cases

```{r n-test-cases, fig.height=14}
ggplot(problem_specifications) +
  aes(fct_reorder(exercise, n_test_cases), n_test_cases) +
  geom_point() +
  coord_flip(ylim = c(0, 100), expand = FALSE, clip = "off") +
  scale_y_continuous(breaks = seq(0, 100, by = 10), position = "right") +
  labs(x = "", y = "number of test cases") +
  theme(plot.margin = unit(c(0, 1, 2, 0), units = "lines"))
```

# Difficulty of the same problems in different languages

```{r difficulty, fig.height=14}
set.seed(254)
ggplot(exercises) +
  aes(fct_reorder(exercise, difficulty), difficulty) +
  stat_summary(fun.y = mean,
               fun.ymin = function(x) mean(x) - sd(x), 
               fun.ymax = function(x) mean(x) + sd(x), 
               geom = "linerange") +
  geom_point(aes(color = language), position = position_jitter(width=0, height=0.2), shape = 1) +
  coord_flip() +
  scale_y_continuous(breaks = 1:10, position = "right") +
  labs(x = "") +
  theme(legend.position = "none")
```

# Average difficulty across languages

```{r ranking, echo=1, fig.height=8}
lang_difficulty_mod <- lme4::lmer(difficulty ~ -1 + language + (1|exercise),
                                  data = exercises)

lang_difficulty_preds <- broom::tidy(lang_difficulty_mod, effects = "fixed") %>%
  rename(language = term) %>%
  mutate(language = str_replace(language, "^language", ""))

ggplot(lang_difficulty_preds) +
  aes(fct_reorder(language, estimate, .desc = TRUE), estimate) +
  geom_linerange(aes(ymin = estimate - std.error, ymax = estimate + std.error)) +
  coord_flip(ylim = c(0, 5.9), expand = FALSE, clip = "off") +
  labs(x = "", y = "average difficulty")
```
